apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-metrics-servicemonitor.yaml
- cluster-monitoring-role.yaml
- cluster-monitoring-role-binding.yaml
- kafka-podmonitors.yaml
- prometheus.yaml
- route.yaml
- service-monitors
- prometheus-monitoring-role.yaml
- prometheus-monitoring-role-binding.yaml
- secrets

namespace: opendatahub
commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: prometheus
generatorOptions:
  disableNameSuffixHash: true

vars:
  - name: namespace
    objref:
      kind: Prometheus
      name: odh-monitoring
      apiVersion: monitoring.coreos.com/v1
    fieldref:
      fieldpath: metadata.namespace

configurations:
  - params.yaml
