apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- servicemonitor.yaml
- kafka-servicemonitor.yaml
- prometheus.yaml
- route.yaml
namespace: opendatahub
commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: prometheus
generatorOptions:
  disableNameSuffixHash: true
