apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    prometheus: k8s
  namespace: prometheus
spec:
  replicas: 1
  serviceAccountName: prometheus-k8s
  securityContext: {}
  serviceMonitorSelector:
      matchLabels:
        team: opendatahub
  podMonitorSelector:
      matchLabels:
        team: opendatahub
  ruleSelector: {}
