apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- anaconda-ce-imagestream.yaml
- anaconda-ce-validator-cron.yaml

commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: anaconda-ce
