apiVersion: v1
kind: ConfigMap
metadata:
  name: odh-jupyterhub-sizes
  labels:
    jupyterhub: singleuser-profiles
data:
  jupyterhub-singleuser-profiles.yaml: |
      sizes:
      - name: Small
        resources:
          requests:
            memory: 8Gi
            cpu: 1
          limits:
            memory: 8Gi
            cpu: 2
      - name: Medium
        resources:
          requests:
            memory: 30Gi
            cpu: 3
          limits:
            memory: 30Gi
            cpu: 6
      - name: Large
        resources:
          requests:
            memory: 60Gi
            cpu: 7
          limits:
            memory: 60Gi
            cpu: 14
      - name: X Large
        resources:
            requests:
              memory: 120Gi
              cpu: 15
            limits:
              memory: 120Gi
              cpu: 30
