apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
- minimal-notebook-imagestream.yaml
- scipy-notebook-imagestream.yaml
- tensorflow-notebook-imagestream.yaml

commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: jupyterhub
