apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
namespace: opendatahub
commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: odh-common
