apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service-account.yaml
- role.yaml
- role-binding.yaml
- operator.yaml
namespace: opendatahub
commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: ailibrary
images:
- name: quay.io/opendatahub/ai-library-operator
  newName: quay.io/opendatahub/ai-library-operator
  newTag: v0.6
generatorOptions:
  disableNameSuffixHash: true
